### ISSUE TITLE
Support for reading colmap scenes

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/OpenSplat#1]
E.g. those in https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip

**Comment by pfxuan** [comment]
It would be more useful if COLMAP GUI can be integrated as a part of the interactive display interface for both sparse SfM and 3DGS reconstruction processes. 
Reference: https://youtu.be/1cN-Oc4Y1Hs?t=14
