### ISSUE TITLE
Cannot view generated .ply image

### ISSUE THREAD

**Issue by CIMBIBOY** [pierotofy/OpenSplat#103]
I successfully train the 3DGS for the banana images and the banana's initial pointcloud but cannot view the produced .ply image in https://playcanvas.com/viewer, after I load a fresh train.... only the background is visible. Would appreciate any help I can get to surpass this issue! 
<img width="1470" alt="Screenshot 2024-06-15 at 3 24 08 PM" src="https://github.com/pierotofy/OpenSplat/assets/140697356/0cc89d6f-2220-453d-a947-59adb19b8d5f">
<img width="1470" alt="Screenshot 2024-06-15 at 3 24 23 PM" src="https://github.com/pierotofy/OpenSplat/assets/140697356/645523ab-8ef4-4bc9-9fa6-59aefccb8bcf">
<img width="1470" alt="Screenshot 2024-06-15 at 3 25 19 PM" src="https://github.com/pierotofy/OpenSplat/assets/140697356/821156a0-9cf9-471a-8a59-9344ca084ea9">

**Comment by pierotofy** [comment]
Can you upload a copy of your .ply file somewhere?

**Comment by CIMBIBOY** [comment]
[Uploading ply_files.zip…]()

**Comment by pierotofy** [comment]
I wonder if this is an issue with playcanvas viewer due to some recent update? The files work fine on https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php

**Comment by CIMBIBOY** [comment]
Indeed they work well. I figured there is something wrong with the viewer, cause the file format looked fine. Thanks for the quick response!

**Comment by CIMBIBOY** [comment]
Flawless support!
