### ISSUE TITLE
fatal error: json.hpp: No such file or directory     2 | #include <json.hpp>

### ISSUE THREAD

**Issue by ichsan2895** [pierotofy/OpenSplat#11]
I got error when building it
```
git clone https://github.com/pierotofy/OpenSplat OpenSplat
cd OpenSplat/
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/workspace/OPENSPLAT/libtorch .. && make -j$(nproc)
```
![image](https://github.com/pierotofy/OpenSplat/assets/60387342/3e82bb73-ae96-41a2-ade6-d92017069747)

Using Runpod environment with this specification
```
Ubuntu 22.04 LTS
Python 3.10
libtorch 2.0.1+cu118
RTX A6000 with 48 GB VRAM
```

**Comment by ichsan2895** [comment]
Well, it works when I change a bit the code
```
git clone --recursive https://github.com/pierotofy/OpenSplat OpenSplat
cd OpenSplat/
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/workspace/OPENSPLAT/libtorch .. && make -j$(nproc)
```
![image](https://github.com/pierotofy/OpenSplat/assets/60387342/78b8a5ec-a17b-45c0-934c-96249ce7b62b)

**Comment by pierotofy** [comment]
Huh, strange, the project doesn't have submodules so the --recursive flag shouldn't be needed. Also the compiler should have looked in the vendor/json library for headers, but for some reason it didn't.

I have modified the code https://github.com/pierotofy/OpenSplat/commit/7c37be4941eb915cf516c0bb0ebb591ec2e80cf2 to explicitly reference the path to that library, hopefully it resolves this issue?

**Comment by ichsan2895** [comment]
I have modified the code https://github.com/pierotofy/OpenSplat/commit/7c37be4941eb915cf516c0bb0ebb591ec2e80cf2 to explicitly reference the path to that library, hopefully it resolves this issue?

> Huh, strange, the project doesn't have submodules so the --recursive flag shouldn't be needed. Also the compiler should have looked in the vendor/json library for headers, but for some reason it didn't.
> 
> I have modified the code [7c37be4](https://github.com/pierotofy/OpenSplat/commit/7c37be4941eb915cf516c0bb0ebb591ec2e80cf2) to explicitly reference the path to that library, hopefully it resolves this issue?

Already fixed with this command. It worked, I never touch it again :100: 
```
git clone --recursive https://github.com/pierotofy/OpenSplat OpenSplat
cd OpenSplat/
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/workspace/OPENSPLAT/libtorch .. && make -j$(nproc)
```
