### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/OpenSplat#12]
Would be cool to get automated docker builds (and CI tests)

**Comment by cyango** [comment]
Interested!

**Comment by pierotofy** [comment]
It's up for grabs if you want to open a pull request!

**Comment by cyango** [comment]
I'm relatively new to this, but I'm trying to run it inside a docker container with the following Dockerfile:

`# Use an official CUDA runtime as a parent image
FROM --platform=linux/amd64 nvidia/cuda:12.3.1-devel-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        python3-pip \
        python3-dev \
        python3-opencv \
        libglib2.0-0 \
        g++ \
        make \
        libopencv-dev \
        wget \
        unzip
        # nvidia-cuda-toolkit


        
RUN wget https://github.com/Kitware/CMake/releases/download/v3.24.1/cmake-3.24.1-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /opt/cmake-3.24.1 \
      && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-3.24.1 \
      && rm /tmp/cmake-install.sh \
      && ln -s /opt/cmake-3.24.1/bin/* /usr/local/bin


# Install any python packages you need
# COPY requirements.txt requirements.txt

# RUN python3 -m pip install -r requirements.txt

# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install libtorch
RUN wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip && \
    unzip libtorch-shared-with-deps-latest.zip && \
    rm libtorch-shared-with-deps-latest.zip

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# # Run cmake when the container launches
# RUN cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -D CMAKE_PREFIX_PATH=/app/libtorch/share/cmake/Torch .
RUN cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DCMAKE_PREFIX_PATH=/libtorch .

RUN make -j$(nproc)


# Set the entrypoint
ENTRYPOINT [ "python3" ]`


I'm getting this error:

"fatal error: cuda_runtime.h: No such file or directory"


How should i solve this?

**Comment by cyango** [comment]
Ok will test it on my Mac using --platform=linux/amd64

**Comment by pfxuan** [comment]
I converted the existing ubuntu build workflow into this docker build. Feel free to give it a try: https://github.com/pierotofy/OpenSplat/pull/30
