### ISSUE TITLE
specific version of LibTorch

### ISSUE THREAD

**Issue by kanster** [pierotofy/OpenSplat#17]
Do you have any specification of the version of LibTorch?

Just encounter a bug "rror: ‘to_string’ is not a member of ‘c10::guts’" while using it with libtorch 2.2.0

**Comment by pierotofy** [comment]
I'm using 2.1.2+cu121 on my machine. If you find a fix, feel free to open a PR? :pray:

**Comment by pfxuan** [comment]
@pierotofy I was able to reproduce above error from [this](https://github.com/pfxuan/OpenSplat/actions/runs/8001186236/job/21851912180#step:7:115) CI build. Before digging into [these backwards incompatible changes](https://github.com/pytorch/pytorch/releases/tag/v2.2.0) in 2.2.0, do you have any insight or suggestion for this compile error?

**Comment by pierotofy** [comment]
I wonder if you can just change `c10::guts::to_string` references to `c10::to_string`.

**Comment by pfxuan** [comment]
PR https://github.com/pierotofy/OpenSplat/pull/19 should be able to address this issue.
