### ISSUE TITLE
compile error, which version of libtorch should i use?

### ISSUE THREAD

**Issue by jeremyxu36** [pierotofy/OpenSplat#22]
OpenSplat/model.cpp:199:35: error: no matching function for call to ‘cat(<brace-enclosed initializer list>, int)’
  199 |     paramState->exp_avg(torch::cat({
      |                         ~~~~~~~~~~^~
  200 |         paramState->exp_avg(),
      |         ~~~~~~~~~~~~~~~~~~~~~~     
  201 |         torch::zeros_like(paramState->exp_avg().index({idcs.squeeze()})).repeat(repeats)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  202 |     }, 0));
      |     ~~~~~                          

OpenSplat/model.cpp:386:35: error: ‘to_string’ is not a member of ‘c10::guts’
  386 |             auto pId = c10::guts::to_string(param.unsafeGetTensorImpl());

**Comment by jeremyxu36** [comment]
@pfxuan Hi, When I compile the program. the upper error occurs. My computer environment is ubuntu18.04+cuda12.1, and the libtorch i use is libtorch-cxx11-abi-shared-with-deps-2.2.1+cu121 downloaded from https://download.pytorch.org/libtorch/cu121/libtorch-cxx11-abi-shared-with-deps-2.2.1%2Bcu121.zip

**Comment by pfxuan** [comment]
@jeremyxu36 It seems like you are using the old code. Try to sync the latest changes.

https://github.com/pierotofy/OpenSplat/blob/fad54000313e47285675187d30c6be50f633409f/model.cpp#L190

**Comment by pierotofy** [comment]
Should be fixed with the latest `main`, feel free to re-open if the issue persists 🙏
