### ISSUE TITLE
Restore original camera orientation, scale when saving scene

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/OpenSplat#34]
During training the model is scaled and oriented.

Before outputting the output PLY, we should scale / rotate the scene back to its original CRS.

**Comment by pfxuan** [comment]
To reserve the metric scale and camera orientation, it might be easier to feed the original sparse point cloud to training code directly. Rotating the trained ply model file would introduce [an extra complicity](https://github.com/graphdeco-inria/gaussian-splatting/issues/176) and quality degradation if it's not handled correctly.

**Comment by pierotofy** [comment]
Potentially useful:

* https://github.com/google/spherical-harmonics
* https://github.com/playcanvas/engine/blob/412d068cf0b1f6f7df400d75b61d0862c036fc7f/src/scene/gsplat/gsplat.js#L259

**Comment by pfxuan** [comment]
Yes, PlayCanvas's implementation works almost faultlessly. It would be even better if OpenSplat can use the compressed ply format as one of saving options along with the rotation and scaling.  
- https://github.com/playcanvas/super-splat/blob/main/src/splat-convert.ts#L129
- https://github.com/mkkellogg/GaussianSplats3D/issues/47#issuecomment-1801360116
