### ISSUE TITLE
Add MSL support

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/OpenSplat#47]
Metal could be a good candidate for getting faster training on Mac.

**Comment by pfxuan** [comment]
People already started building the Apple silicon based rack. It would be amazing if we can leverage M2/M3 chips for 3DGS.

![IMG_5359](https://github.com/pierotofy/OpenSplat/assets/2773827/58199177-d9b3-4232-aaf7-60be7a8162c2)

**Comment by pfxuan** [comment]
With a proper optimization, technically, even a mobile device should have a capability to handle the training part. e.g. Scaniverse iOS app 3.0 supports the end to end 3DGS reconstruction on device.

**Comment by pierotofy** [comment]
#76
