### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by pierotofy** [pierotofy/OpenSplat#5]
It should be possible to port the rasterizer to CPU (maybe via HIP), or simply rewriting it.

It might be slow, but it would give people the freedom to run this stuff without the NVIDIA tax.

**Comment by AndreiSva** [comment]
yes please!

**Comment by pierotofy** [comment]
Work in progress!

**Comment by pierotofy** [comment]
![output](https://github.com/pierotofy/OpenSplat/assets/1951843/9d7eb2e0-460b-4148-964b-545e1db489d2)

Forward and backward passes working.

**Comment by pierotofy** [comment]
Workss! 

![image](https://github.com/pierotofy/OpenSplat/assets/1951843/b939ec2f-5fde-409e-adfd-4ada3463cbe3)

About 100x slower than GPU, but it's a start.

**Comment by pfxuan** [comment]
Wow

**Comment by pierotofy** [comment]
500 iters and still going strong! I will open a PR.

![image](https://github.com/pierotofy/OpenSplat/assets/1951843/bfc7bdb9-34ba-42c9-ac04-2a0a1ef412f6)
