### ISSUE TITLE
Problem with using COLMAP project

### ISSUE THREAD

**Issue by Garshishka** [pierotofy/OpenSplat#72]
Using datasets from here https://github.com/pierotofy/OpenSplat/issues/1#issue-2139060707 I got no problem using OpenSplat.
But when I make my own point cloud in COLMAP (using banana images from example datasets) and then run them in OpenSplat i get an error "Unsupported camera model: 2". What can cause that?
I'm using COLMAP-3.9.1-windows-cuda with GUI and "automatic reconstruction" function, if that's important.

**Comment by Garshishka** [comment]
After some experiments I think I got еру problem. Don't use "Automatic reconstruction". 
It worked with this steps:

1. Feature extraction: check "Shared for all images" and choose camera model PINHOLE. I had SIMPLE_RADIAL and it doesn't work
2. Feature matching on default parameters
3. Reconstruction
4. Export model

With this it worked!

I think this issue can be closed now

**Comment by Jonathan-Gore** [comment]
Interesting, I'm having the exact same issue as you.

I'd love someone with more knowledge give some insight on why the camera model needs to be "PINHOLE" instead of "SIMPLE_RADIAL" before this issue closes. What implications does that have for the reconstruction?

**Comment by pierotofy** [comment]
It should be relatively simple to add support for simple radial. One needs to look at the definition in colmap's source code and check how the undistortion model works. Then adjust https://github.com/pierotofy/OpenSplat/blob/main/colmap.cpp#L46 accordingly.

**Comment by Jonathan-Gore** [comment]
Ok, I'm willing to take a crack at that later today!

**Comment by Jonathan-Gore** [comment]
@Garshishka Support for Simple_Radial should be live if you're building from main! Let me know how it works if you end up using it.
