### ISSUE TITLE
Hard-coded OS version in .github/workflows/cuda/Linux.sh

### ISSUE THREAD

**Issue by morsingher** [pierotofy/OpenSplat#86]
Hi, note that the Ubuntu version passed as --build-arg in the Dockerfile is not propagated to .github/workflows/cuda/Linux.sh:

https://github.com/pierotofy/OpenSplat/blob/4d70016baae090f119eb346d9f9b35d62bb90597/.github/workflows/cuda/Linux.sh#L12

I'm not sure that this is a bug, but surely it would be nice to be consistent. Also, at least for Ubuntu 18.04 and CUDA 11.3, cuDNN is not installed and libtorch fails to build later. Again, I'm not sure that these two things are related. Will update if I have news.

Thanks for your work anyway :)

**Comment by pfxuan** [comment]
Ubuntu 18.04 has reached its end of life, making it challenging to install compatible CUDA and dependency versions. However, I enabled Ubuntu 20.04 based docker build via PR https://github.com/pierotofy/OpenSplat/pull/87 and wish it could provide some help for your current setup.
